export const SEARCH_BOOK   = 'SEARCH_BOOK';
export const BOOK_DETAIL   = 'BOOK_DETAIL';
export const BOOK_CHAPTERS = 'BOOK_CHAPTERS';
export const CHAPTER_CONTENT = 'CHAPTER_CONTENT';
export const START_LOADING = 'START_LOADING';
